import { readFile, writeFile } from 'node:fs/promises'

/**
 * Everything whose code ends up inside dist/. Both MIT and Apache-2.0 require
 * the copyright notice to travel with the copy, so the built app ships this
 * file next to it.
 *
 * Paths are read straight out of node_modules rather than resolved through the
 * package entry points, because a package is free to keep ./package.json out of
 * its "exports" and several do.
 */
const BUNDLED = ['@cantoo/pdf-lib', 'pdfjs-dist', 'react', 'react-dom', 'scheduler']
const LICENCE_FILES = ['LICENSE', 'LICENSE.md', 'LICENCE', 'COPYING', 'NOTICE']

const sections = []
for (const name of BUNDLED) {
  const root = `node_modules/${name}/`
  const manifest = JSON.parse(await readFile(`${root}package.json`, 'utf8'))

  let text = ''
  for (const candidate of LICENCE_FILES) {
    try {
      text = await readFile(root + candidate, 'utf8')
      break
    } catch {
      // try the next spelling
    }
  }
  if (text.trim() === '') throw new Error(`no licence file shipped with ${name}`)

  const rule = '='.repeat(78)
  const home = manifest.homepage ?? manifest.repository?.url ?? ''
  sections.push(`${rule}\n${name} ${manifest.version} — ${manifest.license}\n${home}\n${rule}\n\n${text.trim()}\n`)
}

const header = `THIRD-PARTY NOTICES

convert.in itself is MIT licensed; see LICENSE. The built application bundles
the libraries below, and their licences require the copyright notices to travel
with any copy, so they are reproduced here in full.

Generated by scripts/notices.mjs. Run "npm run notices" after adding or
upgrading a runtime dependency.

`

await writeFile('public/THIRD-PARTY-NOTICES.txt', header + sections.join('\n'))
console.log(`wrote notices for ${BUNDLED.length} bundled packages`)
